name: Compile preview and example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            lfs: true

      - name: Compile the preview
        uses: xu-cheng/latex-action@v2
        with:
          root_file: preview-example.tex

      - name: Compile the example
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lilly-dir.tex

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f preview-examle.pdf lilly-dir.pdf
          git commit -m "Update PDFs by workflow"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

